---
# tasks file for zookeeper-kafka
- name: Install Pre-reqs
  yum:
    name:
      - java-11-openjdk
      - tar

- include_tasks: supervisor.yml

- include_tasks: zookeeper.yml

- include_tasks: kafka.yml
