---
- name: Istall EPEL
  yum:
    name: epel-release
    
- name: Install Supervisor
  yum:
    name: supervisor

- name: Enable Supervisor service
  service:
    name: supervisord
    state: started
    enabled: yes

...
